### ISSUE TITLE
Feature Request: Elixir 1.15 images

### ISSUE THREAD

**Issue by tomtaylor** [CircleCI-Public/cimg-elixir#119]
Now Elixir 1.15 is out it'd be great to see some images cut for it. https://elixir-lang.org/blog/2023/06/19/elixir-v1-15-0-released/

**Comment by ryanbourdais** [comment]
Hi @tomtaylor I just saw this and opened up PR #121, this should be merged soon and resolve this issue

**Comment by ryanbourdais** [comment]
This image is now live.

**Comment by paulo-silva** [comment]
Thank you, @ryanbourdais 🙇 - Do you think we could also have it to Erlang 26.0.1?

**Comment by ryanbourdais** [comment]
Hi @paulo-silva we grab our Erlang releases from [Erlang Solutions](https://www.erlang-solutions.com/downloads/) which currently does not have an Erlang 26.0.1 release. We cut new releases of this image when elixir updates so it should be available then.

**Comment by tomtaylor** [comment]
Thanks for sorting this @ryanbourdais. I wonder if it might be worth looking at a different source for the Erlang/Elixir build images to allow for a faster release?

[Hex has docker images](https://hub.docker.com/r/hexpm/elixir) for almost every combination of Elixir/Erlang you might want, which could be a useful starting point?

**Comment by tomtaylor** [comment]
FWIW, the .deb for 26.0.2 is now out, but I'm experiencing some TLS certificate errors on the domain: https://binaries2.erlang-solutions.com/debian/bullseye/esl-erlang-26/pool/contrib/e/esl-erlang/esl-erlang_26.0.2-1~debian~bullseye_amd64.deb
