### ISSUE TITLE
Allow for other Erlang versions

### ISSUE THREAD

**Issue by VitorTrin** [CircleCI-Public/cimg-elixir#52]
These images do not allow for a different elixir - erlang combinations, which are crucial, as the versions we use in prod must match with the versions used to build the application. Consider the solution used by hexpm/elixir, that builds a lot of elixir-erlang images

**Comment by dokie** [comment]
Yes, since there are breaking changes in many dependent libs on OTP 24 that work fine with Elxiir 1.12.1 and OTP 23.

@VitorTrin What did you pick then for your CircleCI build/test image if not this one?

**Comment by VitorTrin** [comment]
@dokie We are doing the compile and build application steps in the hexpm images and building the image and pushing it in a `circleci/buildpack-deps:stable-curl` image

**Comment by dokie** [comment]
@VitorTrin Also be aware that some of the Hex images contain vulnerabilities which you can find if you use`docker scan` against your choices.

**Comment by felicianotech** [comment]
Hey folks, I wanted to chim in here. We don't currently support this due to added complexity and demand. So far this is the first request I'm seeing for this. Everything here who wants this, if you can upvote the first post, that would be a great. Also sharing this Issue around to garner interests from others would help.

I'm curious, **if** something like this were to be implemented, how many versions of Erlang would you expect to have? For how many Elixir versions would you expect new Erlang versions to land for?

**Comment by VitorTrin** [comment]
The full compatibilty table is here: https://hexdocs.pm/elixir/1.12.1/compatibility-and-deprecations.html
![image](https://user-images.githubusercontent.com/9387059/122123383-4d7a8c00-ce04-11eb-8473-effefdbe357c.png)
If building a script so every combination is too much, at least the oldest suported erlang version and the newest, so people can upgrade one at a time

**Comment by mattste** [comment]
Ran into this issue today with our upgrade to Elixir v1.12. I'm investigating switching us over to [bob's images](https://github.com/hexpm/bob#docker-images) since that's what we already use in production.

**Comment by jersearls** [comment]
also rain into this while attempting to upgrade to Elixir v1.12.

**Comment by felicianotech** [comment]
It looks to me that there's a decent demand here. We will get this implemented. I'll follow in the near future with a GitHub Issue detailing how we see this working, and then with a PR beginning to implement it.

**Comment by ckoch-cars** [comment]
Bump and cross-posting from a support ticket per Zach Hudson.

There are upstream changes (bug fixes) in OTP 24.0.3 that have not been captured in the CircleCI elixir (V 1.12 images). Specifically one of these fixes is for a bug that dialyzer needs to work correctly.

Please update the version of Erlang/OTP in the circle ci elixir image, or add some additional options for users to select alternate combinations or Elixir and OTP.

**Comment by felicianotech** [comment]
This Issue will be to track the request for multiple Erlang versions. For OTP v24.0.3 specifically, I made this Issue: https://github.com/CircleCI-Public/cimg-elixir/issues/58

**Comment by john-griffin** [comment]
Specific selection of the OTP version is crucial for us to guarantee CI runs the same as prod.

**Comment by felicianotech** [comment]
Waiting for this upstream issue: https://github.com/CircleCI-Public/cimg-shared/issues/51

**Comment by JalexChen** [comment]
this request has been handled and currently waiting on PR to update submodule for multiple erlang version support

**Comment by JalexChen** [comment]
Hi @VitorTrin - I just want to give an update here that the feature you requested has been merged and you are able to choose which version you'd like to use. There is currently a PR open that updates the README, but the functionality of gen-dockerfiles for a specific version should generate dockerfiles for specific versions of erlang!
