### ISSUE TITLE
Include Latest Version of Browsers in Image

### ISSUE THREAD

**Issue by bruschke** [CircleCI-Public/cimg-elixir#60]
Would it be possible to include the latest stable versions of the browsers supported by the browser-tools-orb in the -browsers images?  This would allow us to avoid having to install them with each run when we are needing to run tests with Selenium.  Additionally, it would solve the problem that many of us are currently facing with the Chrome install and Google apparently blocking requests.  https://github.com/CircleCI-Public/browser-tools-orb/issues/34

Lastly, there is a typo in the README.md should be -browsers not -browser.

**Comment by BytesGuy** [comment]
Hi! Thanks for opening this issue.

Regarding the browsers, we intentionally do not install these in the images themselves. This would add extra size to the image itself and we would be limited to installing the latest version of browsers that are available at build time - this can quickly become out of date and may additionally not be the versions required by the end user. By installing them via the orb, the end user has greater control over the environment. 

There is an open issue, linked below, to add a warning/documentation around this:

https://github.com/CircleCI-Public/cimg-shared/issues/34

It looks like the linked issue for the browser tools orb was solved on the same day. Another possibility for avoid using the browser tools orb would be to spin a custom docker image using this image as a base. From there you could install the browsers you need so they are configured as required by your jobs.

The readme typo is fixed here, thanks for pointing this out 😄 https://github.com/CircleCI-Public/cimg-elixir/pull/64

I hope this helps! I will close this issue out, but if you have any further comments please just let us know here and re-open the issue if required. Thanks!
